#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Formatear código con Prettier
npm run format:check || {
  echo "❌ Prettier check failed. Running prettier..."
  npm run format
}

# Ejecutar linter
npm run lint
